// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCommandToHistory(arg1:string,arg2:string):Promise<void>;

export function ConnectSSHWithHostKeyCheck(arg1:string):Promise<main.ConnectionResult>;

export function CreateSynonym(arg1:string):Promise<string>;

export function DeleteCustomProfile(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteSavedCommand(arg1:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteInteractiveCommand(arg1:string,arg2:string):Promise<void>;

export function ExecuteSavedCommand(arg1:string,arg2:string):Promise<void>;

export function GetActiveConnections():Promise<Array<string>>;

export function GetActivePortForwards(arg1:string):Promise<Array<main.PortForward>>;

export function GetBaseProfile():Promise<main.SSHConfig>;

export function GetCommandHistory(arg1:string):Promise<Array<string>>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<main.FileInfo>>;

export function ListSavedCommands():Promise<Array<main.SavedCommand>>;

export function LoadProfiles():Promise<Array<main.SSHConfig>>;

export function OpenFileDialog():Promise<string>;

export function PortForward(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<void>;

export function SaveCommand(arg1:string,arg2:string):Promise<void>;

export function SaveCustomProfile(arg1:main.CustomProfile):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function StopInteractiveCommand(arg1:string):Promise<void>;

export function StopPortForward(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;
