// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommandToHistory(arg1, arg2) {
  return window['go']['main']['App']['AddCommandToHistory'](arg1, arg2);
}

export function ConnectSSHWithHostKeyCheck(arg1) {
  return window['go']['main']['App']['ConnectSSHWithHostKeyCheck'](arg1);
}

export function CreateSynonym(arg1) {
  return window['go']['main']['App']['CreateSynonym'](arg1);
}

export function DeleteCustomProfile(arg1) {
  return window['go']['main']['App']['DeleteCustomProfile'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function GetActiveConnections() {
  return window['go']['main']['App']['GetActiveConnections']();
}

export function GetBaseProfile() {
  return window['go']['main']['App']['GetBaseProfile']();
}

export function GetCommandHistory(arg1) {
  return window['go']['main']['App']['GetCommandHistory'](arg1);
}

export function LoadProfiles() {
  return window['go']['main']['App']['LoadProfiles']();
}

export function SaveCustomProfile(arg1) {
  return window['go']['main']['App']['SaveCustomProfile'](arg1);
}
