// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {fs} from '../models';

export function AddCommandToHistory(arg1:string,arg2:string):Promise<void>;

export function ConnectSSH(arg1:main.SSHConfig):Promise<void>;

export function ConnectSSHWithHostKeyCheck(arg1:main.YAMLConfig):Promise<string>;

export function CreateSynonym(arg1:string):Promise<string>;

export function DeleteCustomProfile(arg1:string):Promise<void>;

export function DeleteFile(arg1:main.SSHConfig,arg2:string):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DownloadFile(arg1:main.SSHConfig,arg2:string,arg3:string):Promise<void>;

export function GetActiveConnections():Promise<Array<string>>;

export function GetBaseProfile():Promise<main.YAMLConfig>;

export function GetCommandHistory(arg1:string):Promise<Array<string>>;

export function ListDirectory(arg1:main.SSHConfig,arg2:string):Promise<Array<fs.FileInfo>>;

export function LoadCustomProfiles():Promise<Array<main.YAMLConfig>>;

export function LoadProfiles():Promise<Array<main.YAMLConfig>>;

export function LoadYAMLConfig(arg1:string):Promise<main.YAMLConfig>;

export function LoadYAMLConfigs():Promise<Array<main.YAMLConfig>>;

export function PortForward(arg1:main.SSHConfig,arg2:number,arg3:number):Promise<void>;

export function RenameFile(arg1:main.SSHConfig,arg2:string,arg3:string):Promise<void>;

export function SaveCustomProfile(arg1:main.CustomProfile):Promise<void>;

export function UploadFile(arg1:main.SSHConfig,arg2:string,arg3:string):Promise<void>;
